// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LenisProvider from "@/app/components/lenis-provider"; // Assurez-vous que le chemin est correct
import AnimatedBackground from "@/app/components/animated-background"; // Assurez-vous que le chemin est correct
import Header from "@/app/components/header"; // Importer le Header


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mathis Jeugnet - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}>
        <Header /> {/* <-- Ajouter le Header ici */}
        <div className="fixed top-0 left-0 w-full h-full -z-10">
          <AnimatedBackground />
        </div>
        <LenisProvider>{children}</LenisProvider>
      </body>
    </html>
  );
}